const productosCargados = [
    {
        id: 1,
        img1: '../media/productos/id1.jpg',
        nombre: 'Agenda Semanal',
        formato: 'Papel',
        destacado: 'SI',
        precio: 20000,
    },
    {
        id: 2,
        nombre: 'Agenda Diaria',
        img1: '../media/productos/id2.jpg',
        formato: 'Papel',
        destacado: 'NO',
        precio: 23000,
    },
    {
        id: 3,
        nombre: 'Cuaderno Rayado',
        img1: '../media/productos/id3.jpg',
        formato: 'Papel',
        destacado: 'SI',
        precio: 12000,
    },
    {
        id: 4,
        nombre: 'Cuaderno Liso',
        img1: '../media/productos/id4.jpg',
        formato: 'Papel',
        destacado: 'NO',
        precio: 12000,
    },
    {
        id: 5,
        nombre: 'Planner Diario',
        img1: '../media/productos/id5.png',
        formato: 'Digital',
        destacado: 'SI',
        precio: 18000,
    },
    {
        id: 6,
        nombre: 'Planner Semanal',
        img1: '../media/productos/id6.png',
        formato: 'Digital',
        destacado: 'NO',
        precio: 18000,
    },    

]